# Site settings
title: Erwin's Personal Blog
header-img: img/container-ship.jpg
email: erwin.embsen@gmail.com
description: "My personal technical ramblings!"
baseurl: ""
url: "http://www.ecsn.nl"
twitter_username: eembsen
github_username:  eembsen

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
